### ISSUE TITLE
问h5格式链接怎么看参数？

### ISSUE THREAD

**Issue by SamLu-ECNU** [jiji262/xiaoetong-video-downloader#5]
https://appXXXXXXXX.h5.xiaoeknow.com/content_page/eyJ0eXXXXXXXH0?entry=3&entry_type=0
格式如上。

**Comment by jiji262** [comment]
店铺就是你那个appxxxx

**Comment by SamLu-ECNU** [comment]
> 店铺就是你那个appxxxx

对的，但是resources之类的没法输入啊？

**Comment by mooz04** [comment]
请问一下直播的视频好像是不能下载的是吗？

**Comment by jiji262** [comment]
应该是的

**Comment by lms1206** [comment]
> 请问一下直播的视频好像是不能下载的是吗？

抓到m3u8即可直接下载，建议带上ua防ban
