### ISSUE TITLE
视频无法下载

### ISSUE THREAD

**Issue by youmenputao** [jiji262/xiaoetong-video-downloader#7]
请问我代码运行正常，提示：
进程已结束，退出代码 0

也弹出了二维码图片也扫码了，系统也自动创建了download文件夹和config.json文件，但是并没有下载视频，请问怎么解。

我是用的Pycharm，用的参数是app5DvJRqZS8379 -d p_5e47a2a6c7dfe_aeGWuYUo

有空请帮忙看一下，谢谢

**Comment by jiji262** [comment]
使用的账号需要有访问该课程的权限。

**Comment by youmenputao** [comment]
是的，这个课程是已经买了的

**Comment by youmenputao** [comment]
不过我也是windows系统
