### ISSUE TITLE
现在下载的TS已经无法查看了

### ISSUE THREAD

**Issue by kwshare** [jiji262/xiaoetong-video-downloader#9]
[hls @ 000001abbc9fc240] Opening 'crypto:v_0.ts' for reading
[crypto @ 000001abbd004000] Unable to open resource: v_0.ts
[hls @ 000001abbc9fc240] Failed to open segment 0 of playlist 0
[hls @ 000001abbc9fc240] Opening 'crypto:v_1.ts' for reading
[crypto @ 000001abbc9fd5c0] Unable to open resource: v_1.ts
[hls @ 000001abbc9fc240] Failed to open segment 1 of playlist 0
[hls @ 000001abbc9fc240] Opening 'crypto:v_2.ts' for reading
[crypto @ 000001abbd004000] Unable to open resource: v_2.ts
[hls @ 000001abbc9fc240] Failed to open segment 2 of playlist 0
[hls @ 000001abbc9fc240] Opening 'crypto:v_3.ts' for reading
[crypto @ 000001abbc9fd5c0] Unable to open resource: v_3.ts
[hls @ 000001abbc9fc240] Failed to open segment 3 of playlist 0

是不是这种方法已经失效了？

**Comment by jiji262** [comment]
我这边使用正常，没有发现这个问题

**Comment by Danny8090** [comment]
我想问下，我的在浏览器上面打开课程播放是黑屏，只有通过微信PC端打开才能播放？这是课程设置导致的吗？

**Comment by Danny8090** [comment]
> 
> 
> 我这边使用正常，没有发现这个问题



> 
> 
> 我这边使用正常，没有发现这个问题

我想问下，我的在浏览器上面打开课程播放是黑屏，只有通过微信PC端打开才能播放？这是课程设置导致的吗？

**Comment by kwshare** [comment]
> 
> 
> 我这边使用正常，没有发现这个问题

我想问下，我的在浏览器上面打开课程播放是黑屏，只有通过微信PC端打开才能播放？这是课程设置导致的吗？

**Comment by kwshare** [comment]
找到原因了，这是个用MAC开发的，直接移植到Windows 10就会出现上面的错误！可能需要改进！在MAC上确实运行正常！！！谢谢
